-- AlterTable
ALTER TABLE "StockAdjustments" ADD COLUMN     "adjustDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "StockRequests" ADD COLUMN     "requestDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "StockReturns" ADD COLUMN     "returnDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "StockTransfers" ADD COLUMN     "transferDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
